# Generated by Django 5.2.6 on 2025-10-14 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('jurisdiction', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.IntegerField(primary_key=True, serialize=False)),
                ('voter_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=200)),
                ('party', models.CharField(max_length=50)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_sought', to='api.post')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_candidate', to='api.candidate')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voted_office', to='api.post')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_caster', to='api.voter')),
            ],
        ),
    ]
